version: '3.8'

services:
  php:
    container_name: ss-php-project
    build: ./php
    volumes:
      - ./php:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: ss-mysql-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
