# Use the official NGINX image as the base image
FROM nginx:alpine

# Copy the local HTML files to the NGINX default directory
COPY . /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 80
