apiVersion: v1
kind: Service
metadata:
  name: my-website-service
spec:
  selector:
    app: my-website
  ports:
  - protocol: TCP
    port: 8054  # Port accessible inside the cluster
    targetPort: 8054  # Port on the container
  type: LoadBalancer  # Use NodePort for local clusters like Minikube
